version: '3.5'

services:
  cassandra_hackolade_test:
    image: cassandra:3.0
    container_name: cassandra_hackolade_test
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:
